### ISSUE TITLE
SmartEEPROM functionality

### ISSUE THREAD

**Issue by daemon-blade** [AndrewJo/qmk-drop-alt#1]
HI, I'm really enjoying your custom firmware, the only downside is that it doesn't support the new SmartEEPROM functionality for this keyboard.  Is there any chance you could update your firmware to support this?  Thanks - Iain

**Comment by AndrewJo** [comment]
@daemon-blade Oh, thanks for letting me know! I haven't been using the ALT as my daily driver for a while so I wasn't aware of the new update. I'll look into it in my free time and I'll update the firmware. No guarantees on when that will happen as I'm a new dad and rarely have time for hobbies anymore. 

I'll keep this issue open until I get the firmware updated.

**Comment by daemon-blade** [comment]
Thanks Andrew  Congrats on being a Dad, I've got 4 so no worries, I know
how rare spare time is.

Iain

**Comment by jwjordan** [comment]
What I did was remove the startup mode line in config.h, then compiled my own version and that works to "remember" the last mode and settings that I had enabled. This presumes that you have enabled SmartEEPROM on your Alt already, which is easy enough by following these instructions: https://github.com/nicoelayda/mdloader#quick-start

**Comment by AndrewJo** [comment]
@jwjordan that's great! If you are willing to submit a PR, I would be more than happy to merge it. 👍

**Comment by jwjordan** [comment]
Not sure you want this to be a permanent change though, because it eliminates the startup mode entirely, which would be bad for anyone without SmartEEPROM enabled (I think).

**Comment by daemon-blade** [comment]
Brilliant, I updated to the Smart eeprom so I'll give it a go.

Thanks again.

**Comment by AndrewJo** [comment]
@daemon-blade I've made some updates which will make the changes here compatible with the latest QMK firmware. It also seems to have enabled EEPROM functionality that remembers your settings when unplugged and plugged back in.

I've confirmed that this works on my Drop ALT.

Let me know if you try this and have any issues.
